version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      # The following environment variable is used to enable hot reloading~
      - WATCHPACK_POLLING=true
